version: '3.7'

services:
  movie_web:
    build: 
        context: ..
        dockerfile: ./docker/api/Dockerfile
    command: >
        gunicorn -b 0.0.0.0:4500
        --access-logfile -
        --reload
        "app:app"
    env_file: 
        - ./api/.env
    volumes: 
        - ../api/:/api/
        - ../models/:/models/
    ports: 
        - 4500:4500